x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

services:

  proxy:
    container_name: proxy
    image: traefik:2.11 
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/etc/traefik:ro
      - certs-traefik:/certs:ro
    ports:
      - "80:80" 
      - "443:443"
      - "8080:8080"
    networks:
     - rt-transcriber   
    restart: unless-stopped

  authware-certs:
    image: airenas/authware-certs:${authware_version}
    container_name: authware-certs
    restart: on-failure
    environment:
      - RUST_LOG=info 
      - HOSTS=${HOSTS}
      - CERT_FILE=traefik
    logging: *default-logging  
    volumes:
      - certs-traefik:/certs:rw  

  wrapper:
    image: airenas/rt-transcriber-wrapper:${wrapper_version}
    container_name: rt-wrapper
    logging: *default-logging
    restart: unless-stopped
    networks:
     - rt-transcriber   
    environment:
     - SPEECH_URL=ws://streaming-asr:6006/  
     - JOINER_URL=http://norm-num:3000/invnorm_num
     - PUNCTUATOR_URL=http://text-punctuator:8000/punctuation   
     - REDIS_URL=redis://redis-cache:6379/0
     - REDIS_ENCRYPTIONKEY=${CACHE_ENCRYPTION_KEY}
     - REDIS_TTL=6h
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.kaldi-proxy.rule=PathPrefix(`/{path:(?i)client/}`)"
     - "traefik.http.routers.kaldi-proxy.middlewares=rate-limit@file,authware@docker"
     - "traefik.http.routers.kaldi-proxy.entrypoints=web,websecure"
     - "traefik.http.routers.kaldi-proxy.tls=true"
     - "traefik.http.services.kaldi-proxy.loadbalancer.server.port=8000"  

  redis-cache:
    container_name: redis-cache
    image: redis:7.2.5-alpine3.19
    restart: unless-stopped
    logging: *default-logging   
    networks:
     - rt-transcriber   
    
  authware:
    image: airenas/authware:${authware_version}
    container_name: authware
    environment:
      - RUST_LOG=debug,tower_http=warn,h2=warn,rustls=warn,hyper_util=warn 
      - SESSION_TIMEOUT=6h
      - INACTIVITY_TIMEOUT=30m
      - SAMPLE_USERS=${SAMPLE_USERS}
      - HOST=authware
      - REDIS_URL=redis://redis:6379
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_WS_URL=${AUTH_WS_URL}
      - AUTH_WS_USER=${AUTH_WS_USER}
      - AUTH_WS_PASS=${AUTH_WS_PASS}
      - AUTH_APP_CODE=${AUTH_WS_APP_CODE}
    restart: unless-stopped 
    networks:
     - rt-transcriber
    logging: *default-logging  
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.authware.rule=PathPrefix(`/auth`)"
     - "traefik.http.routers.authware.entrypoints=websecure"
     - "traefik.http.routers.authware.tls=true"
     - "traefik.http.middlewares.authware.forwardauth.address=https://authware:8000/auth"  
     - "traefik.http.middlewares.authware.forwardauth.trustForwardHeader=true"
     - "traefik.http.middlewares.authware.forwardauth.tls.insecureSkipVerify=true"
     - "traefik.http.middlewares.authware.forwardauth.authResponseHeaders=User-Info"
     - "traefik.http.services.authware.loadbalancer.server.port=8000"
     - "traefik.http.services.authware.loadbalancer.server.scheme=https"
     - "traefik.http.services.authware.loadbalancer.serversTransport=skip-verify-tls-transport@file"
    volumes:
      - certs:/certs:rw   

  redis:
    container_name: redis
    image: redis:7.2.5-alpine3.19
    restart: unless-stopped
    logging: *default-logging   
    networks:
     - rt-transcriber
      
  norm-num:
    image: intelektikalt/invnorm-nums:${nnum_version}
    container_name: norm-num
    logging: *default-logging
    restart: unless-stopped
    ports:
      - "6010:3000"
    networks:
     - rt-transcriber   

  rt-transcriber-gui:
    image: airenas/rt-transcriber-gui:${rt_transcriber_gui_version}
    container_name: rt-transcriber-gui
    logging: *default-logging
    restart: unless-stopped
    networks:
     - rt-transcriber   
    environment:
      - BASE_PATH=/${RT_TRANSCRIBER_PATH}/
      - SERVER_URL=${KALDI_WS}
      - DATA_SERVER_URL=${DATA_SERVER_URL}
      - AUTH_URL=${AUTH_URL}
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.rt-transcriber.rule=PathPrefix(`/${RT_TRANSCRIBER_PATH}`)"
     - "traefik.http.routers.rt-transcriber.middlewares=rate-limit@file,rt-transcriber"
     - "traefik.http.middlewares.rt-transcriber.stripprefix.prefixes=/${RT_TRANSCRIBER_PATH}"
     - "traefik.http.routers.rt-transcriber.entrypoints=web,websecure"
     - "traefik.http.routers.rt-transcriber.tls=true"
     - "traefik.http.routers.rt-transcriber.service=rt-transcriber"
     - "traefik.http.services.rt-transcriber.loadbalancer.server.port=8000"     

##########################################################################
  s3-model-sync:
    container_name: s3-model-sync
    image: rclone/rclone:1.73
    volumes:
      - onnx-model-l:/model:rw
    environment:
      - RCLONE_CONFIG_S3_TYPE=s3
      - RCLONE_CONFIG_S3_PROVIDER=Other
      - RCLONE_CONFIG_S3_ENDPOINT=${AWS_ENDPOINT_URL}
      - RCLONE_CONFIG_S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RCLONE_CONFIG_S3_FORCE_PATH_STYLE=true
      - RCLONE_CONFIG_S3_REGION=${AWS_REGION}
    restart: "no"
    logging: *default-logging
    cpus: 2
    mem_limit: 512mb
    memswap_limit: 512mb
    command: sync ${MODEL_BUCKET} /model --progress --transfers=4 --checkers=8 --delete-during --stats=1s

  streaming-asr:
    container_name: streaming-asr-l
    image: airenas/sherpa-onnx-online-websocket-server:0.0.1
    volumes:
      - onnx-model-l:/model:ro
    ports:
      - "6006:6006"
    command: --tokens=/model/tokens.txt --zipformer2-ctc-model=/model/ctc-epoch-10-avg-2-chunk-64-left-256.int8.onnx --num-work-threads=10 --enable-endpoint=true --rule1-must-contain-nonsilence=true --rule1-min-trailing-silence=5 --rule2-min-trailing-silence=3 --rule3-min-utterance-length=60
    restart: unless-stopped
    logging: *default-logging
    cpus: 10
    mem_limit: 4g
    memswap_limit: 4g
    networks:
     - rt-transcriber         
##########################################################################
  punctuator-model-sync:
    container_name: punctuator-model-sync
    image: rclone/rclone:1.73
    volumes:
      - punctuation-model:/model:rw
    environment:
      - RCLONE_CONFIG_S3_TYPE=s3
      - RCLONE_CONFIG_S3_PROVIDER=Other
      - RCLONE_CONFIG_S3_ENDPOINT=${AWS_ENDPOINT_URL}
      - RCLONE_CONFIG_S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RCLONE_CONFIG_S3_FORCE_PATH_STYLE=true
      - RCLONE_CONFIG_S3_REGION=${AWS_REGION}
    restart: "no"
    logging: *default-logging
    cpus: 2
    mem_limit: 512mb
    memswap_limit: 512mb
    command: sync ${PUNCTUATOR_MODEL_BUCKET} /model --progress --transfers=4 --checkers=8 --delete-during --stats=1s 

  text-punctuator:
    container_name: text-punctuator
    image: airenas/text-punctuator:0.2.0
    volumes:
      - punctuation-model:/model:ro
    ports:
      - "6007:8000"
    environment:
      - ONNX_MODEL=/model/model.int8.onnx
      - BPE_VOCAB=/model/bpe.vocab
      - RUST_LOG=debug,hyper=warn,tower_http=warn
    restart: unless-stopped
    logging: *default-logging
    cpus: 2
    mem_limit: 1g
    memswap_limit: 1g
    networks:
     - rt-transcriber  
##########################################################################
networks:
  rt-transcriber:

volumes:
  certs:
  certs-traefik:    
  onnx-model-l:
  punctuation-model: