x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

services:

  proxy:
    container_name: proxy
    image: traefik:2.11 
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/etc/traefik:ro
    ports:
      - "80:80" 
      - "443:443"
      - "8080:8080"
    networks:
     - polis   
    restart: unless-stopped

  manager:
    image: airenas/docker-kaldi-gstreamer-server:${gstreamer_version}
    container_name: manager
    logging: *default-logging
    restart: unless-stopped
    networks:
     - polis   
    entrypoint: ["python", "/opt/kaldi-gstreamer-server/kaldigstserver/master_server.py", "--port=9090"]

  worker:
    image: airenas/docker-kaldi-gstreamer-server:${gstreamer_version}
    # container_name: worker
    logging: *default-logging
    restart: unless-stopped
    entrypoint: ["python", "/opt/kaldi-gstreamer-server/kaldigstserver/worker.py", "-c", "/opt/models/lt.yaml", "-u", "ws://manager:9090/worker/ws/speech"]
    environment:
     - GST_PLUGIN_PATH=/opt/gst-kaldi-nnet2-online/src/:/opt/kaldi/src/gst-plugin/
     - PHONES2WORD_SERVER_URL=http://phones2word:3000/phones2word
    networks:
     - polis    
    volumes:
     - ${MODEL_DIR}:/opt/models:ro  

  wrapper:
    image: airenas/rt-transcriber-wrapper:${wrapper_version}
    container_name: rt-wrapper
    logging: *default-logging
    restart: unless-stopped
    networks:
     - polis   
    environment:
     - STATUS_URL=ws://manager:9090/client/ws/status
     - SPEECH_URL=ws://manager:9090/client/ws/speech  
     - JOINER_URL=http://norm-num:3000/invnorm_num
     - PUNCTUATOR_URL=http://punctuation-service:8000/punctuation   
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.kaldi-proxy.rule=PathPrefix(`/{path:(?i)client/ws}`)"
     - "traefik.http.routers.kaldi-proxy.middlewares=rate-limit@file"
     - "traefik.http.routers.kaldi-proxy.entrypoints=web,websecure"
     - "traefik.http.routers.kaldi-proxy.tls=true"
     - "traefik.http.routers.kaldi-proxy.tls.certResolver=le-resolver"
     - "traefik.http.routers.kaldi-proxy.tls.domains[0].main=${HOST}"
     - "traefik.http.services.kaldi-proxy.loadbalancer.server.port=8000"  

  tensorflow:
    image: tensorflow/serving:1.15.0
    environment:
      MODEL_NAME: punctuation
      MODEL_BASE_PATH: /models
    volumes:  
      - ${PUNCTUATION_DIR}/models:/models
    restart: unless-stopped 
    networks:
     - polis   
    logging: *default-logging
      
  punctuation-service:
    image: airenas/list-punctuation:0.3.1
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${PUNCTUATION_DIR}/3.0:/model
    environment:
      TF_URL: tensorflow:8500 
    networks:
     - polis     
    
  norm-num:
    image: intelektikalt/invnorm-nums:${nnum_version}
    container_name: norm-num
    logging: *default-logging
    restart: unless-stopped
    networks:
     - polis   

  phones2word:
    image: intelektikalt/asr-phoneme2word:0.0.1
    container_name: phones2word
    logging: *default-logging
    restart: unless-stopped  
    networks:
     - polis   

  polis-gui:
    image: airenas/polis-gui:${polis_gui_version}
    container_name: polis-gui
    logging: *default-logging
    restart: unless-stopped
    networks:
     - polis   
    environment:
      - BASE_HREF=/${POLIS_PATH}/
      - KALDI_URL=${KALDI_WS}
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.polis.rule=PathPrefix(`/${POLIS_PATH}`)"
     - "traefik.http.routers.polis.middlewares=rate-limit@file,polis"
     - "traefik.http.middlewares.polis.stripprefix.prefixes=/${POLIS_PATH}"
     - "traefik.http.routers.polis.entrypoints=web,websecure"
     - "traefik.http.routers.polis.tls=true"
     - "traefik.http.routers.polis.tls.certResolver=le-resolver"
     - "traefik.http.routers.polis.tls.domains[0].main=${HOST}"
     - "traefik.http.routers.polis.service=polis"
     - "traefik.http.services.polis.loadbalancer.server.port=8000"     

networks:
  polis: